import 'package:flutter/material.dart';
import 'package:places/res/app_colors.dart';

final lightTheme = ThemeData(
  brightness: Brightness.light,

  appBarTheme: const AppBarTheme(color: AppLightColors.appBackgroundColor),

//     Color? canvasColor,
//     Color? cardColor,
//     ColorScheme? colorScheme,
//     Color? colorSchemeSeed,
//     Color? dialogBackgroundColor,
//     Color? disabledColor,
//     Color? dividerColor,
//     Color? focusColor,
//     Color? highlightColor,°
//     Color? hintColor,
//     Color? hoverColor,
//     Color? indicatorColor,
//     Color? primaryColor,
//     Color? primaryColorDark,
//     Color? primaryColorLight,
//     MaterialColor? primarySwatch,
//     Color? scaffoldBackgroundColor,
//     Color? secondaryHeaderColor,
//     Color? shadowColor,
//     Color? splashColor,
//     Color? unselectedWidgetColor,
//     // TYPOGRAPHY & ICONOGRAPHY
//     String? fontFamily,
//     List<String>? fontFamilyFallback,
//     String? package,
//     IconThemeData? iconTheme,
//     IconThemeData? primaryIconTheme,
//     TextTheme? primaryTextTheme,
//     TextTheme? textTheme,
//     Typography? typography,
//     // COMPONENT THEMES
//     AppBarTheme? appBarTheme,
//     BadgeThemeData? badgeTheme,
//     MaterialBannerThemeData? bannerTheme,
//     BottomAppBarTheme? bottomAppBarTheme,
//     BottomNavigationBarThemeData? bottomNavigationBarTheme,
//     BottomSheetThemeData? bottomSheetTheme,
//     ButtonBarThemeData? buttonBarTheme,
//     ButtonThemeData? buttonTheme,
//     CardTheme? cardTheme,
//     CheckboxThemeData? checkboxTheme,
//     ChipThemeData? chipTheme,
//     DataTableThemeData? dataTableTheme,
//     DialogTheme? dialogTheme,
//     DividerThemeData? dividerTheme,
//     DrawerThemeData? drawerTheme,
//     DropdownMenuThemeData? dropdownMenuTheme,
//     ElevatedButtonThemeData? elevatedButtonTheme,
//     ExpansionTileThemeData? expansionTileTheme,
//     FilledButtonThemeData? filledButtonTheme,
//     FloatingActionButtonThemeData? floatingActionButtonTheme,
//     IconButtonThemeData? iconButtonTheme,
//     ListTileThemeData? listTileTheme,
//     MenuBarThemeData? menuBarTheme,
//     MenuButtonThemeData? menuButtonTheme,
//     MenuThemeData? menuTheme,
//     NavigationBarThemeData? navigationBarTheme,
//     NavigationDrawerThemeData? navigationDrawerTheme,
//     NavigationRailThemeData? navigationRailTheme,
//     OutlinedButtonThemeData? outlinedButtonTheme,
//     PopupMenuThemeData? popupMenuTheme,
//     ProgressIndicatorThemeData? progressIndicatorTheme,
//     RadioThemeData? radioTheme,
//     SegmentedButtonThemeData? segmentedButtonTheme,
//     SliderThemeData? sliderTheme,
//     SnackBarThemeData? snackBarTheme,
//     SwitchThemeData? switchTheme,
//     TabBarTheme? tabBarTheme,
//     TextButtonThemeData? textButtonTheme,
//     TextSelectionThemeData? textSelectionTheme,
//     TimePickerThemeData? timePickerTheme,
//     ToggleButtonsThemeData? toggleButtonsTheme,
//     TooltipThemeData? tooltipTheme,
);

final darkTheme = ThemeData();
